name: side_header_list_view
description: ListView with sticky headers on the side. Inspired by the Android contacts app and the calendar app.
version: 1.0.0-nullsafety.0
homepage: https://github.com/renefloor/side_header_list_view

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.2
